### ISSUE TITLE
Update PubMed

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#964] opened 2023-10-17 22:49 UTC
### Prefix

pubmed

### Explanation

Can we please set the "Preferred Prefix" for `pubmed` to "PMID" ?

It looks like `PMID` is advertized by pubmed?
e.g: https://pubmed.ncbi.nlm.nih.gov/37118671/
<img width="456" alt="Screen Shot 2023-10-17 at 3 32 48 PM" src="https://github.com/biopragmatics/bioregistry/assets/4561292/2d45697b-9ece-4ed6-90de-0e5fa597234f">

### Contributor ORCID

0000-0002-8719-7760

**Comment by cthoyt** [comment] 2023-10-17 23:08
duplicate of #323

**Closed** 2023-10-17 23:36 UTC
Labels: Update
