### ISSUE TITLE
enable "alternative prefix" searching in the autocomplete on bioregistry.io

### ISSUE THREAD

**Issue by sierra-moxon** [biopragmatics/bioregistry#555] opened 2022-09-07 21:56 UTC
use case: I searched bioregistry for the "SCTID" prefix advertised by SNOMEDCT, to make sure we had it represented, but it didn't come up in the autocomplete (which I would expect to redirect me to the SNOMEDCT prefix page).  I then went to the SNOMEDCT page itself to look for synonyms and I just missed the SCTID prefix (the list of alternative prefixes is long for this record).

Is it possible to add the "alternative prefixes" to the autocomplete list used in bioregistry.io (if matched on an alias, I would expect the search to take me to the official page)? 

Alternatively, if I could search bioregistry without selecting a prefix from the autocomplete pulldown, and that search allowed me to search across synonyms, that would be great.

**Comment by cthoyt** [comment] 2022-09-07 22:04
Yes that’s a great idea. I swear somewhere in the tracker there’s already a duplicate of this

**Comment by cthoyt** [comment] 2022-09-09 11:33
I added an initial implementation but I didn't write the vue.js code that actually runs the autocomplete so it's going to take some time to figure it out and make the user experience nicer

**Comment by cthoyt** [comment] 2022-10-25 11:02
Hi @sierra-moxon, I've finally taken another pass (and mucked through some messy old Vue.js code) to get this working in #557. It'll get merged today and deployed tonight.

**Closed** 2022-10-25 11:36 UTC
Labels: New
